name = x_player_api
title = X Player API
author = SaKeL
description = Manages player visuals and realistic character animations. Fully replaces and overrides player_api.
min_minetest_version = 5.10.0
min_luanti_version = 5.10.0
supported_games = *
depends =
optional_depends = player_api

